M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu26.04.1 date 2026-07-24T16:59:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-24T16:59:21-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-42.0
X77.0Y-5.0
X77.0Y-42.0
M30
